version: '3'
services:
  user-db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_USER: mozz
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - booking-app
    restart: unless-stopped

  user-api:
    image: mozdev/eventgrid-api:latest
    container_name: user-api
    ports:
      - "8088:8082"
    depends_on:
      - user-db
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user
    networks:
      - booking-app


volumes:
  db:
networks:
  booking-app: